name: Publish to NPM

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: '24.x'
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: npm ci
        working-directory: ./kfs-vite

      - name: Publish to NPM
        run: npm publish
        working-directory: ./kfs-vite
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}